routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth','namespace' => 'Web'], static function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');

    Route::resource('category', 'CategoryController');
    Route::get('category/delete/{category}', 'CategoryController@destroy')->name('category.delete');
    Route::get('category/update/status/{status}/{category}', 'CategoryController@updateStatus')->name('category.update.status');

    Route::resource('usaha', 'UsahaController');
    Route::get('usaha/delete/{usaha}','UsahaController@destroy')->name('usaha.delete');
    Route::get('usaha/update/status/{status}/{usaha}','UsahaController@updateStatus')->name('usaha.update.status');

    Route::resource('alamatusaha', 'AlamatUsahaController');
    Route::get('alamatusaha/create/{usaha}','AlamatUsahaController@create')->name('alamatusaha.create');
    Route::get('alamatusaha/delete/{alamatusaha}','AlamatUsahaController@destroy')->name('alamatusaha.delete');
    Route::get('alamatusaha/update/status/{status}/{alamatusaha}','AlamatUsahaController@updateStatus')->name('alamatusaha.update.status');

    Route::resource('modalprofit','ModalProfitController');
    Route::get('modalprofit/create/{usaha}','ModalProfitController@create')->name('modalprofit.create');

    Route::resource('foto', 'FotoController');
    Route::get('foto/create/{usaha}','FotoController@create')->name('foto.create');
    Route::get('foto/delete/{foto}','FotoController@destroy')->name('foto.delete');
    Route::get('foto/update/status/{status}/{foto}','FotoController@updateStatus')->name('foto.update.status');

    Route::resource('video', 'VideoController');
    Route::get('video/create/{usaha}','VideoController@create')->name('video.create');
    Route::get('video/delete/{video}','VideoController@destroy')->name('video.delete');
    Route::get('video/update/status/{status}/{video}','VideoController@updateStatus')->name('video.update.status');

    Route::get('review/update/status/{status}/{review}','ReviewController@updateStatus')->name('review.update.status');

    Route::resource('berita', 'BeritaController');
    Route::get('berita/delete/{berita}', 'BeritaController@destroy')->name('berita.delete');
    Route::get('berita/update/status/{status}/{berita}', 'BeritaController@updateStatus')->name('berita.update.status');

    Route::resource('user', 'UserController');
    Route::get('user/delete/{user}', 'UserController@destroy')->name('user.delete');
    Route::get('user/update/status/{status}/{user}', 'UserController@updateStatus')->name('user.update.status');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Routing\UrlGenerator;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id',
        'name',
        'email',
        'password',
        'address',
        'address_type',
        'role',
        'picture',
        'is_active'
    ];

    protected $appends = ['picture_url'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @return UrlGenerator|null|string
     */
    public function getPictureUrlAttribute(){
        if(isset($this->attributes['picture'])) {
            return url(asset('images/' . $this->attributes['picture']));
        }

        return null;
    }
}

app/Http/Controllers/Web/UserController.php
<?php

namespace App\Http\Controllers\Web;

use App\Constants\AddressType;
use App\Constants\Role;
use App\Models\User;
use Illuminate\Contracts\View\Factory;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;

class UserController extends Controller
{
    /**
     * @param Request $request
     * @return Factory|View
     */
    public function index(Request $request){
        $users = User::when($request->has('q'), static function (Builder $query) use ($request){
            return $query->where('name', 'like', '%'.$request->get('q').'%')
                        ->orwhere('email', 'like', '%'.$request->get('q').'%')
                        ->orwhere('role', 'like', '%'.$request->get('q').'%');
        })
            ->orderBy('name')
            ->paginate();

        return view('users.index', compact('users'));
    }

    /**
     * @return Factory|View
     * @throws \ReflectionException
     */
    public function create(){
        $addresstypes = AddressType::all();
        $roles = Role::all();
        return view('users.create', compact('roles', 'addresstypes'));
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     * @throws ValidationException
     */
    public function store(Request $request){
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required',
            'password' => 'required',
            'role' => 'required'
        ]);

        $input = $request->all();
        if($request->has('image')){
            $image = $request->image;
            $ext2 = $image->getClientOriginalExtension();
            $newName2 = random_int(100000, 1001238912) . '.' . $ext2;
            $image->move(public_path('images'), $newName2);
            $input +=[
                'picture' => $newName2
            ];
        }

        $user = new User();
        $user->password = bcrypt($request->get('password'));
        $user->fill($input);
        $user->save()
            ? flash('Data created')->success()
            : flash('Data failed to create')->error();

        return redirect()->route('user.index');
    }

    /**
     * @param User $user
     * @return Factory|View
     * @throws \ReflectionException
     */
    public function edit(User $user){
        $addresstypes = AddressType::all();
        $roles = Role::all();
        return view('users.edit', compact('user', 'roles', 'addresstypes'));
    }

    /**
     * @param Request $request
     * @param User $user
     * @return RedirectResponse
     * @throws ValidationException
     */
    public function update(Request $request, User $user){
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required',
            'role' => 'required',
        ]);

        if($request->has('image')){
            $image = $request->image;
            $ext2 = $image->getClientOriginalExtension();
            $newName2 = random_int(100000, 1001238912) . '.' . $ext2;
            $image->move(public_path('images'), $newName2);
            $user->picture = $newName2;
        }
        if($request->has('password')) {
            $user->password = bcrypt($request->get('password'));
        }

        $user->name = $request->get('name');
        $user->email = $request->get('email');
        $user->address = $request->get('address');
        $user->address_type = $request->get('address_type');
        $user->role = $request->get('role');
        $user->update()
            ? flash('Data updated')->success()
            : flash('Data failed to update')->error();

        return redirect()->route('user.index');
    }

    /**
     * @param User $user
     * @return RedirectResponse
     * @throws \Exception
     */
    public function destroy(User $user){
        $user->delete()
            ? flash('Data deleted')->success()
            : flash('Data failed to delete')->error();

        return redirect()->route('user.index');
    }

    /**
     * @param $status
     * @param User $user
     */
    public function updateStatus($status, User $user){
        $user->is_active = $status;
        $user->save();
    }
}

resources/views/users/create.blade.php
@extends('layouts.sidenav')

@section('content')
    <div class="box">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Add New Users</h3>
            </div>

            <form method="post" action="{{ route('user.store') }}" enctype="multipart/form-data" accept-charset="UTF-8">
                @csrf
                <div class="box-body">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control"  name="name" id="name" placeholder="name" required>
                    </div>
                    <div class="form-group">
                        <label for="name">Email</label>
                        <input type="email" class="form-control"  name="email" id="email" placeholder="email" required>
                    </div>
                    <div class="form-group">
                        <label for="name">Password</label>
                        <input type="password" class="form-control"  name="password" id="password" placeholder="password" required>
                    </div>
                    <div class="form-group">
                        <label for="picture">Picture</label>
                        <input type="file" name="image">
                    </div>
                    <div class="form-group">
                        <label>Select Address Type</label>
                        <select class="form-control" name="address_type">
                            <option value=" ">No Data</option>
                            @foreach($addresstypes as $key => $addresstype)
                                <option value="{{ $key }}">{{ $addresstype }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Role</label>
                        <select class="form-control" name="role">
                            @foreach($roles as $key => $role)
                                <option value="{{ $key }}">{{ $role }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="name">Address</label>
                        <textarea class="form-control" name="address" placeholder="address" ></textarea>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
            </form>
        </div>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.sidenav')

@section('content')
    <div class="box">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Edit Users</h3>
            </div>

            <form method="post" action="{{ route('user.update', $user) }}" enctype="multipart/form-data" accept-charset="UTF-8">
                @csrf
                @method('PUT')
                <div class="box-body">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" value="{{ $user->name }}" class="form-control"  name="name" id="name" placeholder="name" required>
                    </div>
                    <div class="form-group">
                        <label for="name">Email</label>
                        <input type="email" value="{{ $user->email }}" class="form-control"  name="email" id="email" placeholder="email" required>
                    </div>
                    <div class="form-group">
                        <label for="name">Password</label>
                        <input type="password" class="form-control"  name="password" id="password" placeholder="password">
                    </div>
                    <div class="form-group">
                        <label for="picture">Picture</label>
                        <input type="file" name="image">
                    </div>
                    <div class="form-group">
                        <label>Select Address Type</label>
                        <select class="form-control" name="address_type">
                            <option value="">No Data</option>
                            @foreach($addresstypes as $key => $addresstype)
                                <option value="{{ $key }}" @if($user->address_type == $key) selected @endif>{{ $addresstype }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Role</label>
                        <select class="form-control" name="role">
                            @foreach($roles as $key => $role)
                                <option value="{{ $key }}" @if($user->role == $key) @endif>{{ $role }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="name">Address</label>
                        <textarea class="form-control" name="address" placeholder="address" >{{  $user->address }}</textarea>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
            </form>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.sidenav')

@section('content')
    <style>
        .switch {
            position: relative;
            display: inline-block;
            width: 60px;
            height: 34px;
        }

        .switch input {
            opacity: 0;
            width: 0;
            height: 0;
        }

        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ccc;
            -webkit-transition: .4s;
            transition: .4s;
        }

        .slider:before {
            position: absolute;
            content: "";
            height: 26px;
            width: 26px;
            left: 4px;
            bottom: 4px;
            background-color: white;
            -webkit-transition: .4s;
            transition: .4s;
        }

        input:checked+.slider {
            background-color: #2196F3;
        }

        input:focus+.slider {
            box-shadow: 0 0 1px #2196F3;
        }

        input:checked+.slider:before {
            -webkit-transform: translateX(26px);
            -ms-transform: translateX(26px);
            transform: translateX(26px);
        }

        .slider.round {
            border-radius: 34px;
        }

        .slider.round:before {
            border-radius: 50%;
        }
    </style>

    @include('flash::message')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Users Management</h3>
            <div class="box-tools">
                <form class="row">
                    <div class="input-group input-group-sm hidden-xs" style="width: 150px;">
                        <input class="form-control" placeholder="{{ __('Search') }}&hellip;" name="q" value="{{ request('q') }}">
                        <div class="input-group-btn">
                            <button class="btn btn-secondary"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="box-body no-padding">
            <a href="{{ route('user.create') }}"  style="margin-left: 10px"  class="btn btn-sm btn-default"><span class="fa fa-plus"></span> Add New</a>

            @if(!$users->isEmpty())
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th class="text-center" style="width: 20px">No.</th>
                        <th>{{ __('Profile') }}</th>
                        <th>{{ __('Name') }}</th>
                        <th>{{ __('Address') }}</th>
                        <th>{{ __('Role') }}</th>
                        <th>{{ __('Active') }}</th>
                        <th class="text-center pull-right">{{ __('Action') }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $i => $user)
                        <tr>
                            <td>{{ $i+1 }}</td>
                            <td>
                                @if($user->picture)
                                    <img width="80px" height="80px" src="{{ $user->picture_url  }}">
                                @else
                                    -
                                @endif
                            </td>
                            <td>{{ $user->name }}
                                <div class="text-muted small">
                                    {{ $user->email }}
                                </div>
                            </td>
                            <td>{{ $user->address }}
                                <div class="text-muted small">
                                    @if($user->address_type)
                                    {{ \App\Constants\AddressType::getTitle($user->address_type) }}
                                    @else
                                        -
                                    @endif
                                </div>
                            </td>
                            <td>{{ \App\Constants\Role::getTitle($user->role)  }}</td>
                            <td>
                                <label class="switch">
                                    <input class="quickpick" data-status="{{$user->id}}" name="quick_pick" type="checkbox" @if($user->is_active == 1) checked @endif>
                                    <span class="slider round"></span>
                                </label>
                            </td>
                            <td class="text-center pull-right" >
                                <div class="btn-group">
                                    <a href="{{ route('user.edit', $user) }}" class="btn btn-sm btn-warning">
                                        <i class="fa fa-pencil"></i>
                                    </a>
                                    <a href="{{ route('user.delete', $user) }}" class="btn btn-sm btn-danger"
                                       onclick = "return confirm('Are you sure ?')">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <center>{{ $users->links() }}</center>
            @else
                <div class="px-3 text-center" style="padding: 10px">
                    <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
                        No Data
                    </p>
                </div>
            @endif
        </div>
    </div>
@endsection

@push('scripts')
    <script type="text/javascript">
        $('.quickpick').on('click', function () {
            console.log('aaa');

            let id = $(this).data('status')
            let url = $(this).prop('checked')
                ? "{{ url('user/update/status/1/') }}" + '/' + id
                : "{{ url('user/update/status/0/') }}" + '/' + id

            $.ajax({
                url: url,
                success: function (response) {
                }
            })
        })
    </script>
@endpush