routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth','namespace' => 'Web'], static function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');

    Route::resource('category', 'CategoryController');
    Route::get('category/delete/{category}', 'CategoryController@destroy')->name('category.delete');
    Route::get('category/update/status/{status}/{category}', 'CategoryController@updateStatus')->name('category.update.status');

    Route::resource('usaha', 'UsahaController');
    Route::get('usaha/delete/{usaha}','UsahaController@destroy')->name('usaha.delete');
    Route::get('usaha/update/status/{status}/{usaha}','UsahaController@updateStatus')->name('usaha.update.status');

    Route::resource('alamatusaha', 'AlamatUsahaController');
    Route::get('alamatusaha/create/{usaha}','AlamatUsahaController@create')->name('alamatusaha.create');
    Route::get('alamatusaha/delete/{alamatusaha}','AlamatUsahaController@destroy')->name('alamatusaha.delete');
    Route::get('alamatusaha/update/status/{status}/{alamatusaha}','AlamatUsahaController@updateStatus')->name('alamatusaha.update.status');

    Route::resource('modalprofit','ModalProfitController');
    Route::get('modalprofit/create/{usaha}','ModalProfitController@create')->name('modalprofit.create');

    Route::resource('foto', 'FotoController');
    Route::get('foto/create/{usaha}','FotoController@create')->name('foto.create');
    Route::get('foto/delete/{foto}','FotoController@destroy')->name('foto.delete');
    Route::get('foto/update/status/{status}/{foto}','FotoController@updateStatus')->name('foto.update.status');

    Route::resource('video', 'VideoController');
    Route::get('video/create/{usaha}','VideoController@create')->name('video.create');
    Route::get('video/delete/{video}','VideoController@destroy')->name('video.delete');
    Route::get('video/update/status/{status}/{video}','VideoController@updateStatus')->name('video.update.status');

    Route::get('review/update/status/{status}/{review}','ReviewController@updateStatus')->name('review.update.status');

    Route::resource('berita', 'BeritaController');
    Route::get('berita/delete/{berita}', 'BeritaController@destroy')->name('berita.delete');
    Route::get('berita/update/status/{status}/{berita}', 'BeritaController@updateStatus')->name('berita.update.status');

    Route::resource('user', 'UserController');
    Route::get('user/delete/{user}', 'UserController@destroy')->name('user.delete');
    Route::get('user/update/status/{status}/{user}', 'UserController@updateStatus')->name('user.update.status');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/ModalProfit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ModalProfit extends Model
{
    protected $fillable = [
        'modal',
        'profit',
        'presentase_bagi_pendana',
        'jumlah_hari_persiapan',
        'periode_transaksi_per_hari'
    ];

    /**
     * @return BelongsTo
     */
    public function usaha(){
        return $this->belongsTo(Usaha::class);
    }
}

app/Http/Controllers/Web/ModalProfitController.php
<?php

namespace App\Http\Controllers\Web;

use App\Models\ModalProfit;
use App\Models\Usaha;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;

class ModalProfitController extends Controller
{
    /**
     * @param Usaha $usaha
     * @return Factory|View
     */
    public function create(Usaha $usaha){
        return view('modal-profit.create', compact('usaha'));
    }

    /**
     * @param Request $request
     * @return Factory|View
     * @throws ValidationException
     */
    public function store(Request $request){
        $this->validate($request,[
            'modal' => 'required',
            'profit' => 'required',
            'usaha_id' => 'required',
            'presentase_bagi_pendana' => 'required',
            'jumlah_hari_persiapan' => 'required',
            'periode_transaksi_per_hari' => 'required'
        ]);

        $modalProfit = new ModalProfit();
        $modalProfit->fill($request->all());
        $modalProfit->usaha()->associate($request->get('usaha_id'));
        $modalProfit->save()
            ? flash('Data berhasil disimpan!')->success()
            : flash('Data gagal disimpan!')->error();

        return redirect()->route('usaha.show', $request->get('usaha_id'));
    }

    /**
     * @param ModalProfit $modalprofit
     * @return Factory|View
     */
    public function edit(ModalProfit $modalprofit){
        return view('modal-profit.edit', compact('modalprofit'));
    }

    /**
     * @param Request $request
     * @param ModalProfit $modalProfit
     * @return RedirectResponse
     * @throws ValidationException
     */
    public function update(Request $request, ModalProfit $modalprofit){
        $this->validate($request,[
            'modal' => 'required',
            'profit' => 'required',
            'usaha_id' => 'required',
            'presentase_bagi_pendana' => 'required',
            'jumlah_hari_persiapan' => 'required',
            'periode_transaksi_per_hari' => 'required'
        ]);

        $modalprofit->fill($request->all());
        $modalprofit->usaha()->associate($request->get('usaha_id'));
        $modalprofit->update()
            ? flash('Data berhasil diupdate!')->success()
            : flash('Data gagal diupdate!')->error();

        return redirect()->route('usaha.show', $request->get('usaha_id'));
    }


}

resources/views/modal-profit/create.blade.php
@extends('layouts.sidenav')

@section('content')
    <div class="box">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Add New Modal & Profit</h3>
            </div>

            <form method="post" action="{{ route('modalprofit.store') }}">
                @csrf
                <input type="hidden" name="usaha_id" value="{{ $usaha->id }}">
                <div class="box-body">
                    <div class="form-group">
                        <label for="name">Modal</label> <p style="font-style: italic">*) masukkan tanpa Rp dan tanpa titik apabila angka ribuan</p>
                        <input type="number" min="0" class="form-control"  name="modal" id="name" placeholder="modal">
                    </div>

                    <div class="form-group">
                        <label for="name">Profit</label> <p style="font-style: italic">*) masukkan tanpa Rp dan tanpa titik apabila angka ribuan</p>
                        <input type="number" min="0" class="form-control"  name="profit" id="name" placeholder="profit">
                    </div>
                    <div class="form-group">
                        <label for="name">Presentasi Bagi Pendana</label> <p style="font-style: italic">*) masukkan tanpa % </p>
                        <input type="number" min="0" class="form-control"  name="presentase_bagi_pendana" id="name" placeholder="presentase bagi pendana">
                    </div>
                    <div class="form-group">
                        <label for="name">Jumlah Hari Persiapan</label> <p style="font-style: italic">*) masukkan tanpa hari</p>
                        <input type="number" min="0" class="form-control"  name="jumlah_hari_persiapan" id="name" placeholder="jumlah hari pesiapan">
                    </div>
                    <div class="form-group">
                        <label for="name">Periode Transaksi Per Hari</label> <p style="font-style: italic">*) masukkan tanpa hari</p>
                        <input type="number" min="0" class="form-control"  name="periode_transaksi_per_hari" id="name" placeholder="periode transaksi per hari">
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
            </form>
        </div>
    </div>
@endsection

resources/views/modal-profit/edit.blade.php
@extends('layouts.sidenav')

@section('content')
    <div class="box">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Edit Modal & Profit</h3>
            </div>

            <form method="post" action="{{ route('modalprofit.update', $modalprofit) }}">
                @csrf
                @method('PUT')
                <input type="hidden" name="usaha_id" value="{{ $modalprofit->usaha_id }}">
                <div class="box-body">
                    <div class="form-group">
                        <label for="name">Modal</label> <p style="font-style: italic">*) masukkan tanpa Rp dan tanpa titik apabila angka ribuan</p>
                        <input type="number" value="{{ $modalprofit->modal }}" min="0" class="form-control"  name="modal" id="name" placeholder="modal">
                    </div>

                    <div class="form-group">
                        <label for="name">Profit</label> <p style="font-style: italic">*) masukkan tanpa Rp dan tanpa titik apabila angka ribuan</p>
                        <input type="number" min="0" value="{{ $modalprofit->profit }}" class="form-control"  name="profit" id="name" placeholder="profit">
                    </div>
                    <div class="form-group">
                        <label for="name">Presentasi Bagi Pendana</label> <p style="font-style: italic">*) masukkan tanpa % </p>
                        <input type="number" min="0" value="{{ $modalprofit->presentase_bagi_pendana }}" class="form-control"  name="presentase_bagi_pendana" id="name" placeholder="presentase bagi pendana">
                    </div>
                    <div class="form-group">
                        <label for="name">Jumlah Hari Persiapan</label> <p style="font-style: italic">*) masukkan tanpa hari</p>
                        <input type="number" min="0" class="form-control" value="{{ $modalprofit->jumlah_hari_persiapan }}" name="jumlah_hari_persiapan" id="name" placeholder="jumlah hari pesiapan">
                    </div>
                    <div class="form-group">
                        <label for="name">Periode Transaksi Per Hari</label> <p style="font-style: italic">*) masukkan tanpa hari</p>
                        <input type="number" min="0" class="form-control"  name="periode_transaksi_per_hari" value="{{ $modalprofit->periode_transaksi_per_hari }}" id="name" placeholder="periode transaksi per hari">
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
            </form>
        </div>
    </div>
@endsection