routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth','namespace' => 'Web'], static function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');

    Route::resource('category', 'CategoryController');
    Route::get('category/delete/{category}', 'CategoryController@destroy')->name('category.delete');
    Route::get('category/update/status/{status}/{category}', 'CategoryController@updateStatus')->name('category.update.status');

    Route::resource('usaha', 'UsahaController');
    Route::get('usaha/delete/{usaha}','UsahaController@destroy')->name('usaha.delete');
    Route::get('usaha/update/status/{status}/{usaha}','UsahaController@updateStatus')->name('usaha.update.status');

    Route::resource('alamatusaha', 'AlamatUsahaController');
    Route::get('alamatusaha/create/{usaha}','AlamatUsahaController@create')->name('alamatusaha.create');
    Route::get('alamatusaha/delete/{alamatusaha}','AlamatUsahaController@destroy')->name('alamatusaha.delete');
    Route::get('alamatusaha/update/status/{status}/{alamatusaha}','AlamatUsahaController@updateStatus')->name('alamatusaha.update.status');

    Route::resource('modalprofit','ModalProfitController');
    Route::get('modalprofit/create/{usaha}','ModalProfitController@create')->name('modalprofit.create');

    Route::resource('foto', 'FotoController');
    Route::get('foto/create/{usaha}','FotoController@create')->name('foto.create');
    Route::get('foto/delete/{foto}','FotoController@destroy')->name('foto.delete');
    Route::get('foto/update/status/{status}/{foto}','FotoController@updateStatus')->name('foto.update.status');

    Route::resource('video', 'VideoController');
    Route::get('video/create/{usaha}','VideoController@create')->name('video.create');
    Route::get('video/delete/{video}','VideoController@destroy')->name('video.delete');
    Route::get('video/update/status/{status}/{video}','VideoController@updateStatus')->name('video.update.status');

    Route::get('review/update/status/{status}/{review}','ReviewController@updateStatus')->name('review.update.status');

    Route::resource('berita', 'BeritaController');
    Route::get('berita/delete/{berita}', 'BeritaController@destroy')->name('berita.delete');
    Route::get('berita/update/status/{status}/{berita}', 'BeritaController@updateStatus')->name('berita.update.status');

    Route::resource('user', 'UserController');
    Route::get('user/delete/{user}', 'UserController@destroy')->name('user.delete');
    Route::get('user/update/status/{status}/{user}', 'UserController@updateStatus')->name('user.update.status');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Berita.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Berita extends Model
{
    protected $appends = ['image_url'];
    protected $fillable = [
          'title',
          'slug',
          'image',
          'berita',
          'status'
    ];

    /**
     * @return BelongsTo
     */
    public function user(){
        return $this->belongsTo(User::class);
    }


    /**
     * @return UrlGenerator|null|string
     */
    public function getImageUrlAttribute(){
        if(isset($this->attributes['image'])) {
            return url(asset('images/' . $this->attributes['image']));
        }

        return null;
    }
}

app/Http/Controllers/API/BeritaController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Berita;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BeritaController extends Controller
{
    /**
     * @return JsonResponse
     */
    public function index(){
        $beritas = Berita::orderBy('created_at', 'desc')->limit(5)->get();

        return response()->json([
            'status'   => 'success',
            'message'  => 'Data Retrieved!',
            'code'     => 200,
            'payload'  => $beritas
        ]);
    }
}

app/Http/Controllers/Web/BeritaController.php
<?php

namespace App\Http\Controllers\Web;

use App\Models\Berita;
use Illuminate\Contracts\View\Factory;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;

class BeritaController extends Controller
{
    /**
     * @param Request $request
     * @return Factory|View
     */
    public function index(Request $request){
        $beritas = Berita::orderBy('created_at','desc')
                ->when($request->has('q'), static function(Builder $query) use ($request){
                    return $query->where('title', 'like', '%'.$request->get('q').'%');
                })
                ->paginate();
        return view('berita.index', compact('beritas'));
    }

    /**
     * @return Factory|View
     */
    public function create(){
        return view('berita.create');
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     * @throws \Exception
     */
    public function store(Request $request){
        try {
            $this->validate($request, [
                'title' => 'required',
                'picture' => 'required',
                'berita' => 'required'
            ]);
        } catch (ValidationException $e) {
            flash($e->getMessage());
            return redirect()->back();
        }

        $input = $request->all();
        $slug = str_replace(' ', '-', $request->get('title'));
        $input +=[
            'slug' => $slug
        ];

        if($request->has('picture')){
            $image = $request->picture;
            $ext2 = $image->getClientOriginalExtension();
            $newName2 = random_int(100000, 1001238912) . '.' . $ext2;
            $image->move(public_path('images'), $newName2);
            $input +=[
                'image' => $newName2
            ];
        }

        $berita = new Berita();
        $berita->fill($input);
        $berita->user()->associate($request->user());
        $berita->save()
            ? flash('Data berhasil disimpan!')->success()
            : flash('Data gagal disimpan!')->error();

        return redirect()->route('berita.index');
    }

    /**
     * @param $id
     * @return Factory|View
     */
    public function edit($id){
        $berita = Berita::find($id);
        return view('berita.edit', compact('berita'));
    }

    /**
     * @param Request $request
     * @param $id
     * @return RedirectResponse
     * @throws \Exception
     */
    public function update(Request $request, $id){
        try {
            $this->validate($request, [
                'title' => 'required',
                'berita' => 'required'
            ]);
        } catch (ValidationException $e) {
            flash($e->getMessage());
            return redirect()->back();
        }

        $berita = Berita::find($id);

        $input = $request->all();
        $slug = str_replace(' ', '-', $request->get('title'));
        $input +=[
          'slug' => $slug
        ];

        if($request->has('picture')){
            $image = $request->picture;
            $ext2 = $image->getClientOriginalExtension();
            $newName2 = random_int(100000, 1001238912) . '.' . $ext2;
            $image->move(public_path('images'), $newName2);
            $input +=[
                'image' => $newName2
            ];
        }

        $berita->fill($input);
        $berita->user()->associate($request->user());
        $berita->update()
            ? flash('Data berhasil diubah!')->success()
            : flash('Data gagal diubah!')->error();

        return redirect()->route('berita.index');
    }

    /**
     * @param Berita $berita
     * @return RedirectResponse
     * @throws \Exception
     */
    public function destroy(Berita $berita){
        $berita->delete()
            ? flash('Data berhasil dihapus!')->success()
            : flash('Data gagal disimpan!')->error();

        return redirect()->route('berita.index');
    }

    /**
     * @param $id
     * @return Factory|View
     */
    public function show($id){
        $berita = Berita::find($id);
        return view('berita.show', compact('berita'));
    }

    /**
     * @param $status
     * @param Berita $berita
     */
    public function updateStatus($status, Berita $berita){
        $berita->status = $status;
        $berita->save();
    }
}

resources/views/berita/create.blade.php
@extends('layouts.sidenav')

@section('content')
    <div class="box">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Add New Berita</h3>
            </div>

            <form method="post" action="{{ route('berita.store') }}" enctype="multipart/form-data" accept-charset="UTF-8">
                @csrf
                <div class="box-body">
                    <div class="form-group">
                        <label for="name">Title</label>
                        <input type="text" class="form-control"  name="title" id="name" placeholder="judul">
                    </div>
                    <div class="form-group">
                        <label for="picture">Picture</label>
                        <input type="file" name="picture" required>
                    </div>
                    <div class="form-group">
                        <label for="name">Content</label>
                        <textarea class="form-control" name="berita"></textarea>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
            </form>
        </div>
    </div>
@endsection

resources/views/berita/edit.blade.php
@extends('layouts.sidenav')

@section('content')
    <div class="box">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Edit Berita</h3>
            </div>

            <form method="post" action="{{ route('berita.update', $berita) }}" enctype="multipart/form-data" accept-charset="UTF-8">
                @csrf
                @method('PUT')
                <div class="box-body">
                    <div class="form-group">
                        <label for="name">Title</label>
                        <input type="text" class="form-control" value="{{ $berita->title }}"  name="title" id="name" placeholder="judul">
                    </div>
                    <div class="form-group">
                        <label for="picture">Picture</label>
                        <input type="file" name="picture">
                    </div>
                    <div class="form-group">
                        <label for="name">Content</label>
                        <textarea class="form-control" name="berita">{{ $berita->berita }}</textarea>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
            </form>
        </div>
    </div>
@endsection

resources/views/berita/index.blade.php
@extends('layouts.sidenav')

@section('content')
    <style>
        .switch {
            position: relative;
            display: inline-block;
            width: 60px;
            height: 34px;
        }

        .switch input {
            opacity: 0;
            width: 0;
            height: 0;
        }

        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ccc;
            -webkit-transition: .4s;
            transition: .4s;
        }

        .slider:before {
            position: absolute;
            content: "";
            height: 26px;
            width: 26px;
            left: 4px;
            bottom: 4px;
            background-color: white;
            -webkit-transition: .4s;
            transition: .4s;
        }

        input:checked+.slider {
            background-color: #2196F3;
        }

        input:focus+.slider {
            box-shadow: 0 0 1px #2196F3;
        }

        input:checked+.slider:before {
            -webkit-transform: translateX(26px);
            -ms-transform: translateX(26px);
            transform: translateX(26px);
        }

        .slider.round {
            border-radius: 34px;
        }

        .slider.round:before {
            border-radius: 50%;
        }
    </style>

    @include('flash::message')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Berita</h3>
            <div class="box-tools">
                <form class="row">
                    <div class="input-group input-group-sm hidden-xs" style="width: 150px;">
                        <input class="form-control" placeholder="{{ __('Search') }}&hellip;" name="q" value="{{ request('q') }}">
                        <div class="input-group-btn">
                            <button class="btn btn-secondary"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="box-body no-padding">
            <a href="{{ route('berita.create') }}"  style="margin-left: 10px"  class="btn btn-sm btn-default"><span class="fa fa-plus"></span> Add New</a>

            @if(!$beritas->isEmpty())
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th class="text-center" style="width: 20px">No.</th>
                        <th>{{ __('TItle') }}</th>
                        <th>{{ __('Image Title') }}</th>
                        <th>{{ __('Content') }}</th>
                        <th>{{ __('Created By') }}</th>
                        <th>{{ __('Active') }}</th>
                        <th class="text-center pull-right">{{ __('Action') }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($beritas as $i => $berita)
                        <tr>
                            <td>{{ $i+1 }}</td>
                            <td>
                                <img width="80px" height="80px" src="{{ $berita->image_url  }}">
                            </td>
                            <td>{{ $berita->title }}
                                <div class="text-muted small">
                                    {{ $berita->slug }}
                                </div>
                            </td>
                            <td>{{ substr($berita->berita, 0, 30) .'...' }}</td>
                            <td>{{ $berita->user->name }}</td>
                            <td>
                                <label class="switch">
                                    <input class="quickpick" data-status="{{$berita->id}}" name="quick_pick" type="checkbox" @if($berita->status == 1) checked @endif>
                                    <span class="slider round"></span>
                                </label>
                            </td>
                            <td class="text-center pull-right" >
                                <div class="btn-group">
                                    <a href="{{ route('berita.show',$berita) }}" class="btn btn-sm btn-info">
                                        <i class="fa fa-info"></i>
                                    </a>
                                    <a href="{{ route('berita.edit', $berita) }}" class="btn btn-sm btn-warning">
                                        <i class="fa fa-pencil"></i>
                                    </a>
                                    <a href="{{ route('berita.delete', $berita) }}" class="btn btn-sm btn-danger"
                                       onclick = "return confirm('Are you sure ?')">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <center>{{ $beritas->links() }}</center>
            @else
                <div class="px-3 text-center" style="padding: 10px">
                    <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
                        No Data
                    </p>
                </div>
            @endif
        </div>
    </div>
@endsection

@push('scripts')
    <script type="text/javascript">
        $('.quickpick').on('click', function () {

            let id = $(this).data('status')
            let url = $(this).prop('checked')
                ? "{{ url('berita/update/status/1/') }}" + '/' + id
                : "{{ url('berita/update/status/0/') }}" + '/' + id

            $.ajax({
                url: url,
                success: function (response) {
                }
            })
        })
    </script>
@endpush

resources/views/berita/show.blade.php
@extends('layouts.sidenav')

@section('content')
    <style>
        .switch {
            position: relative;
            display: inline-block;
            width: 60px;
            height: 34px;
        }

        .switch input {
            opacity: 0;
            width: 0;
            height: 0;
        }

        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ccc;
            -webkit-transition: .4s;
            transition: .4s;
        }

        .slider:before {
            position: absolute;
            content: "";
            height: 26px;
            width: 26px;
            left: 4px;
            bottom: 4px;
            background-color: white;
            -webkit-transition: .4s;
            transition: .4s;
        }

        input:checked+.slider {
            background-color: #2196F3;
        }

        input:focus+.slider {
            box-shadow: 0 0 1px #2196F3;
        }

        input:checked+.slider:before {
            -webkit-transform: translateX(26px);
            -ms-transform: translateX(26px);
            transform: translateX(26px);
        }

        .slider.round {
            border-radius: 34px;
        }

        .slider.round:before {
            border-radius: 50%;
        }
    </style>


    @include('flash::message')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title"></h3>
        </div>

        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12 col-md-12">
                    <div class="card">
                        <div class="card-header bg-light">
                            <strong>Detail Berita</strong><br/>
                            <img style="margin-top: 20px;" width="400px" height="400px" src="{{ $berita->image_url }}">
                        </div>
                        <ul class="list-group list-group-flush" style="margin-top: 20px">
                            <li class="list-group-item">
                                <strong class="text-muted">Title</strong>
                                <span class="pull-right">{{ $berita->title }}</span>
                            </li>
                            <li class="list-group-item">
                                <strong class="text-muted">Created By</strong>
                                <span class="pull-right">{{ $berita->user->name }}</span>
                            </li>
                            <li class="list-group-item">
                                <strong class="text-muted">Created At</strong>
                                <span class="pull-right">{{ $berita->created_at }}</span>
                            </li>
                            <li class="list-group-item">
                                <strong class="text-muted">Content</strong>
                                </br>
                                <span>{{ $berita->berita }}</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection